version: '2'
services:
  artemis:
    container_name: artemis
    image: quay.io/artemiscloud/activemq-artemis-broker
    #ports:
    #  - "8161:8161"
    #  - "61616:61616"
    #  - "5672:5672"
    network_mode:  "host"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      AMQ_EXTRA_ARGS: 
      TZ: Asia/Taipei